// Code generated by float_nocgo.go.tmpl. DO NOT EDIT.

//+build !amd64 !cgo

package float

// AddTo  for []float32
func (f32 F32) AddTo(dst, a, b []float32) {
	f32.vanillaAddTo(dst, a, b)

}

// SubTo  for []float32
func (f32 F32) SubTo(dst, a, b []float32) {
	f32.vanillaSubTo(dst, a, b)

}

// MulTo  for []float32
func (f32 F32) MulTo(dst, a, b []float32) {
	f32.vanillaMulTo(dst, a, b)

}

// ScaleTo  for []float32
func (f32 F32) ScaleTo(dst, a []float32, scale float32) {
	f32.vanillaScaleTo(dst, a, scale)

}

// Sum for []float32
func (f32 F32) Sum(a []float32) float32 {
	{
		return f32.vanillaSum(a)
	}
}

// Dot for []float32
func (f32 F32) Dot(a, b []float32) float32 {
	{
		return f32.vanillaDot(a, b)
	}
}

// AddTo  for []float64
func (f64 F64) AddTo(dst, a, b []float64) {
	f64.vanillaAddTo(dst, a, b)

}

// SubTo  for []float64
func (f64 F64) SubTo(dst, a, b []float64) {
	f64.vanillaSubTo(dst, a, b)

}

// MulTo  for []float64
func (f64 F64) MulTo(dst, a, b []float64) {
	f64.vanillaMulTo(dst, a, b)

}

// ScaleTo  for []float64
func (f64 F64) ScaleTo(dst, a []float64, scale float64) {
	f64.vanillaScaleTo(dst, a, scale)

}

// Sum for []float64
func (f64 F64) Sum(a []float64) float64 {
	{
		return f64.vanillaSum(a)
	}
}

// Dot for []float64
func (f64 F64) Dot(a, b []float64) float64 {
	{
		return f64.vanillaDot(a, b)
	}
}
